FROM maven
# RUN apt-get update && apt-get install -qy curl
# RUN curl -o rootless-install.sh -fsSL https://get.docker.com/rootless
# RUN sh rootless-install.sh
# RUN export PATH=$HOME/bin:$PATH
# RUN export DOCKER_HOST=unix://$XDG_RUNTIME_DIR/docker.sock
# RUN apt-get update && \
#     apt-get -qy full-upgrade && \
#     apt-get install -qy curl && \
#     apt-get install -qy curl && \
#     curl -sSL https://get.docker.com/ | sh
# ENV DOCKER_HOST=unix:///var/run/docker.sock
# apt-get clean && rm -rf /var/lib/apt/lists/*


