- name: create directory for mounting ebs volume for Jenkins
  hosts: all
  become: yes
  tasks:
    - name: create Jenkins directory
      ansible.builtin.file:
        path: /jenkins
        state: directory
        owner: root
        mode: '0777'

- name: Mount EBS volume for Jenkins_home data
  hosts: all
  become: yes
  tasks:
    - name: mount volume
      ansible.posix.mount:
        path: /jenkins
        src: /dev/xvdh
        fstype: xfs
        state: mounted