variable vpc_id {}
variable my_ip {}
variable env_prefix {}
variable instance_type {}
variable subnet_id {}
variable avail_zone {}
variable instance_name {}
variable vpc_cidr_block_for_sg {}
variable jenkins_node_ip {}
